### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by liujun93** [cosmology-tech/starship#298]
log from `check_tx`

```
      log: 'recovered: runtime error: invalid memory address or nil pointer dereference\n' +
        'stack:\n' +
        'goroutine 19052 [running]:\n' +
        'runtime/debug.Stack()\n' +
        '\truntime/debug/stack.go:24 +0x65\n' +
        'github.com/cosmos/cosmos-sdk/baseapp.newDefaultRecoveryMiddleware.func1({0x2534dc0, 0x41bbcb0})\n' +
        '\tgithub.com/cosmos/cosmos-sdk@v0.46.10/baseapp/recovery.go:71 +0x27\n' +
        'github.com/cosmos/cosmos-sdk/baseapp.newRecoveryMiddleware.func1({0x2534dc0?, 0x41bbcb0?})\n' +
        '\tgithub.com/cosmos/cosmos-sdk@v0.46.10/baseapp/recovery.go:39 +0x30\n' +
        'github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x2534dc0, 0x41bbcb0}, 0xc00347ad80?)\n' +
        '\tgithub.com/cosmos/cosmos-sdk@v0.46.10/baseapp/recovery.go:28 +0x37\n' +
        'github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x2534dc0, 0x41bbcb0}, 0x2f0c300?)\n' +
        '\tgithub.com/cosmos/cosmos-sdk@v0.46.10/baseapp/recovery.go:33 +0x5e\n' +
        'github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()\n' +
        '\tgithub.com/cosmos/cosmos-sdk@v0.46.10/baseapp/baseapp.go:658 +0xf0\n' +
        'panic({0x2534dc0, 0x41bbcb0})\n' +
        '\truntime/panic.go:884 +0x212\n' +
        'math/big.(*Int).Sign(...)\n' +
        '\tmath/big/int.go:38\n' +
        'github.com/cosmos/cosmos-sdk/types.Int.Sign(...)\n' +
        '\tgithub.com/cosmos/cosmos-sdk@v0.46.10/types/int.go:204\n' +
        'github.com/cosmos/cosmos-sdk/types.Coin.IsPositive(...)\n' +
        '\tgithub.com/cosmos/cosmos-sdk@v0.46.10/types/coin.go:137\n' +
        'github.com/cosmos/cosmos-sdk/types.Coins.Validate({0xc005322d98, 0x2b?, 0x0?})\n' +
        '\tgithub.com/cosmos/cosmos-sdk@v0.46.10/types/coin.go:218 +0x75\n' +
        'github.com/cosmos/cosmos-sdk/types.Coins.IsValid(...)\n' +
        '\tgithub.com/cosmos/cosmos-sdk@v0.46.10/types/coin.go:268\n' +
        'github.com/cosmos/cosmos-sdk/x/bank/types.MsgSend.ValidateBasic({{0xc005b6c630, 0x2b}, {0xc005b6c660, 0x2b}, {0xc005322d98, 0x1, 0x1}})\n' +
        '\tgithub.com/cosmos/cosmos-sdk@v0.46.10/x/bank/types/msgs.go:42 +0x191\n' +
        'github.com/cosmos/cosmos-sdk/baseapp.validateBasicTxMsgs({0xc00119a6a0?, 0x1, 0x135?})\n' +
        '\tgithub.com/cosmos/cosmos-sdk@v0.46.10/baseapp/baseapp.go:576 +0x7a\n' +
        'github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc0001796c0, 0x0, {0xc00340e3c0, 0x135, 0x135})\n' +
        '\tgithub.com/cosmos/cosmos-sdk@v0.46.10/baseapp/baseapp.go:691 +0x425\n' +
        'github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).CheckTx(0xc0001796c0, {{0xc00340e3c0?, 0xc00294c228?, 0xc00294c120?}, 0x4c10590?})\n' +
        '\tgithub.com/cosmos/cosmos-sdk@v0.46.10/baseapp/abci.go:257 +0x135\n' +
        'github.com/tendermint/tendermint/abci/client.(*localClient).CheckTxAsync(0xc000ff4d80, {{0xc00340e3c0?, 0xd3b580?, 0xc0012be500?}, 0x4c106a8?})\n' +
        '\tgithub.com/tendermint/tendermint@v0.34.24/abci/client/local_client.go:104 +0x118\n' +
        'github.com/tendermint/tendermint/proxy.(*appConnMempool).CheckTxAsync(0xc0012be500?, {{0xc00340e3c0?, 0x155?, 0x80?}, 0x7f?})\n' +
        '\tgithub.com/tendermint/tendermint@v0.34.24/proxy/app_conn.go:126 +0x26\n' +
        'github.com/tendermint/tendermint/mempool/v0.(*CListMempool).CheckTx(0xc001125110, {0xc00340e3c0, 0x135, 0x135}, 0x2ef5720?, {0x9260?, {0x0?, 0xc005991110?}})\n' +
        '\tgithub.com/tendermint/tendermint@v0.34.24/mempool/v0/clist_mempool.go:254 +0x32d\n' +
        'github.com/tendermint/tendermint/rpc/core.BroadcastTxCommit(0xc006c27c40, {0xc00340e3c0, 0x135, 0x135})\n' +
        '\tgithub.com/tendermint/tendermint@v0.34.24/rpc/core/mempool.go:91 +0x468\n' +
        'reflect.Value.call({0x24f5540?, 0x2c310e0?, 0x30?}, {0x28064d3, 0x4}, {0xc005970030, 0x2, 0x18?})\n' +
        '\treflect/value.go:584 +0x8c5\n' +
        'reflect.Value.Call({0x24f5540?, 0x2c310e0?, 0x1a5?}, {0xc005970030?, 0xc005998aa0?, 0xc004b9fb80?})\n' +
        '\treflect/value.go:368 +0xbc\n' +
        'github.com/tendermint/tendermint/rpc/jsonrpc/server.makeJSONRPCHandler.func1({0x2ef3a00, 0xc005322af8}, 0xc004c04900)\n' +
        '\tgithub.com/tendermint/tendermint@v0.34.24/rpc/jsonrpc/server/http_json_handler.go:108 +0x11f9\n' +
        'github.com/tendermint/tendermint/rpc/jsonrpc/server.handleInvalidJSONRPCPaths.func1({0x2ef3a00?, 0xc005322af8?}, 0x4000806878?)\n' +
        '\tgithub.com/tendermint/tendermint@v0.34.24/rpc/jsonrpc/server/http_json_handler.go:140 +0x5d\n' +
        'net/http.HandlerFunc.ServeHTTP(0xc004b9fc80?, {0x2ef3a00?, 0xc005322af8?}, 0xc004c118a8?)\n' +
        '\tnet/http/server.go:2109 +0x2f\n' +
        'net/http.(*ServeMux).ServeHTTP(0xc000182400?, {0x2ef3a00, 0xc005322af8}, 0xc004c04900)\n' +
        '\tnet/http/server.go:2487 +0x149\n' +
        'github.com/tendermint/tendermint/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP({{0x2ed4680?, 0xc001134b80?}, 0x42f9c7?}, {0x2ef3a00?, 0xc005322af8}, 0xc004c04900)\n' +
        '\tgithub.com/tendermint/tendermint@v0.34.24/rpc/jsonrpc/server/http_server.go:256 +0x124\n' +
        'github.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1({0x2ef4060?, 0xc0050c27e0}, 0xc004c04900)\n' +
        '\tgithub.com/tendermint/tendermint@v0.34.24/rpc/jsonrpc/server/http_server.go:229 +0x37f\n' +
        'net/http.HandlerFunc.ServeHTTP(0x0?, {0x2ef4060?, 0xc0050c27e0?}, 0x7a63b4?)\n' +
        '\tnet/http/server.go:2109 +0x2f\n' +
        'net/http.serverHandler.ServeHTTP({0x2edb0b0?}, {0x2ef4060, 0xc0050c27e0}, 0xc004c04900)\n' +
        '\tnet/http/server.go:2947 +0x30c\n' +
        'net/http.(*conn).serve(0xc004a25400, {0x2ef5758, 0xc001348840})\n' +
        '\tnet/http/server.go:1991 +0x607\n' +
        'created by net/http.(*Server).Serve\n' +
        '\tnet/http/server.go:3102 +0x4db\n' +
```

**Comment by Anmol1696** [comment]
Seems to be on the client side.
